# permissions for end users to view preauthkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preauthkey-viewer-role
rules:
- apiGroups:
  - headscale.barpilot.io
  resources:
  - preauthkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - headscale.barpilot.io
  resources:
  - preauthkeys/status
  verbs:
  - get
